repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # последняя стабильная версия на момент чтения
    hooks:
      - id: black
        language_version: python3.9  # укажите вашу версию

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
